{\rtf1\ansi\ansicpg1252\cocoartf1652
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # iOS CircleCI 2.0 configuration file\
#\
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details\
#\
version: 2\
jobs:\
  build:\
\
    # Specify the Xcode version to use\
    macos:\
      xcode: \'939.4.1\'94\
\
    steps:\
      - checkout\
\
      # Install CocoaPods\
      - run:\
          name: Install CocoaPods\
          command: pod install\
\
      # Build the app and run tests\
      - run:\
          name: Build and run tests\
          command: fastlane scan\
          environment:\
            SCAN_DEVICE: iPhone X\
            SCAN_SCHEME: F5OClockTests\
\
      # Collect XML test results data to show in the UI,\
      # and save the same XML files under test-results folder\
      # in the Artifacts tab\
      - store_test_results:\
          path: test_output/report.xml\
      - store_artifacts:\
          path: /tmp/test-results\
          destination: scan-test-results\
      - store_artifacts:\
          path: ~/Library/Logs/scan\
          destination: scan-logs\
\
}